### ISSUE TITLE
Bug in "make" for CentOS

### ISSUE THREAD

**Issue by bradcater** [gnosek/nginx-upstream-fair#1]
I have nginx running without upstream-fair. When compiling with upstream-fair, I get the following output: http://files.bradcater.webfactional.com/nginx_upstream_errors.txt (I tried pasting this in, but the formatting was terrible.)

What have I overlooked?

**Comment by gnosek** [comment]
Do you really attempt to compile upstream-fair with nginx 0.4.1? Sorry but that's not supported. Apart from possible minor build-time issues, upstream-fair should compile and run on nginx 0.5, 0.6 (that's what EPEL ships IIRC, upstream-fair included), 0.7 and 0.8.
